name: build

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 0'
      # min hour day month day-of-week

env:
  IMAGE_NAME: vnc-ros2-humble
  TAG: cuda
  DOCKER_ORGANIZATION: ghcr.io/k-nish

jobs:
  repos:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: k-nish
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        tags: ${{ env.DOCKER_ORGANIZATION }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        push: true
